export const T = {
  primary: '#a07850',
  primaryLight: '#f5ede0',
  primaryText: '#fdf6ec',
  sidebar: '#faf7f2',
  previewBg: '#fff',
  border: '#e0d9cf',
  borderStrong: '#c9a882',
  muted: '#9c7d5e',
  ink: '#3d2f1f',
  inkSoft: '#9c7d5e',
  hint: '#b0a898',
  hole: '#c8bfb3',
  font: 'system-ui, "Segoe UI", Roboto, "Hiragino Sans", "Noto Sans JP", sans-serif',
  radiusMd: 8,
  radiusLg: 12,
};
