export const T = {
  primary: '#4a5f78',
  primaryLight: '#f0ebe3',
  primaryText: '#3d4f63',
  sidebar: '#faf7f2',
  previewBg: '#eeeae4',
  border: '#e8e2d9',
  borderStrong: '#d8d0c4',
  muted: '#6b635c',
  ink: '#2a2420',
  inkSoft: '#4a4540',
  font: 'system-ui, "Segoe UI", Roboto, "Hiragino Sans", "Noto Sans JP", sans-serif',
  radiusMd: 9,
  radiusLg: 12,
};
