export const T = {
  primary: '#5b7fa6',
  primaryLight: '#e8eef5',
  primaryText: '#3d6491',
  sidebar: '#fafafa',
  previewBg: '#f0f0f0',
  border: '#efefef',
  borderStrong: '#e0e0e0',
  muted: '#888',
  ink: '#1c1c1c',
  inkSoft: '#444',
  font: 'system-ui, "Segoe UI", Roboto, "Hiragino Sans", "Noto Sans JP", sans-serif',
  radiusMd: 9,
  radiusLg: 12,
};
